name = "pdf-reader-backend"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "PDF_STORAGE"
id = "982f90a97dc5409886aec7eaa0a7bfcc"
preview_id = "def056015f38458ba1fbce6d82b9d616"

[build]
command = "npm run build:worker"

# R2 bucket for PDF storage (commented out until R2 is enabled)
# [[r2_buckets]]
# binding = "PDF_BUCKET"
# bucket_name = "pdf-reader-files"
# preview_bucket_name = "pdf-reader-files-preview"

# Pages configuration
pages_build_output_dir = "build"
